languageCode = "de-de"
title = "Blue Fate"
baseURL = "https://agitated-sinoussi-fd6eb8.netlify.app/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Über die Band"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "concerts"
    name = "Konzerte"
    url = "/concerts/"
[params]
  # set below parameter to define a favicon
  favicon = "/banjo_mirrored.png"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
[params.posts]
  folderName = "posts"
  pageSize = "6"
  featuredPost = true
  paginationPages = 2
  showFirstLast = false

#[languages]
#[languages.en]
#  languageName = "English"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
