languageCode = "de-de"
title = "Blue Fate"
baseURL = "https://www.bluefate.de/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
defaultContentLanguage = "de"
uglyURLs = true

[outputFormats.HTML]
# We want the filenames for calendar entries to be title.ics,
# but we also want the normal html site to have (what Hugo calls) pretty urls.
# Sadly, Hugo does not provide a way to set the only the calendar URLs to ugly,
# so we have to set uglyURLs = true globally, and deactivate the setting for html.
# See https://discourse.gohugo.io/t/individual-filenames-for-output-formats/34163
noUgly = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Über die Band"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "concerts"
    name = "Konzerte"
    url = "/concerts/"
[params]
  netlifyForms = true
  # set below parameter to define a favicon
  favicon = "/banjo_mirrored.png"
  # set to change date format
  dateFormat = ":date_long" # allows translation, limited to presets
  impressum = "/impressum/"
  gdpr = "/gdpr/"
  attribution_in_footer = false # attribution is on the Impressum page

# Below parameters can be set to override default post settings
[params.posts]
  folderName = "posts"
  pageSize = "6"
  featuredPost = false
  staticPost = true
  staticFile = "welcome.md"
  paginationPages = 2
  showFirstLast = false

[languages]
[languages.de]
  languageName = "Deutsch"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
